# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/wurh
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
mathjax: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  sam博客: http://fsiaonma.github.io/
  joel博客: http://shenjoel.github.io/
  firewood博客: http://firewood1122.github.io
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo: true
duoshuo_shortname: wurh

# Baidu share
baidushare: true

####Baidu Analytics
baidu_analytics:
  enable: true
  id: 391982416296a0d54221f59fe35250d4 # your baidu analytics id