# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo:
  enable: true  ## duoshuo.com
  short_name:  wurh

# Baidu share
baidushare: true

####Baidu Analytics
baidu_analytics:
  enable: true
  id: 391982416296a0d54221f59fe35250d4 # your baidu analytics id